/**
 * BackendStack assertion tests.
 *
 * Verifies that BackendStack synthesizes correctly, instantiates all
 * expected constructs, and creates the right resource types.
 */
import * as cdk from 'aws-cdk-lib';
import { Template } from 'aws-cdk-lib/assertions';
import { PlatformStack } from '../lib/platform-stack';
import { BackendStack } from '../lib/backend-stack';
import { createMockConfig, mockSsmContext, MOCK_ACCOUNT, MOCK_REGION } from './helpers/mock-config';

describe('BackendStack', () => {
  let template: Template;

  beforeAll(() => {
    // Provide domain + certs so all constructs can synthesize.
    // Artifacts distribution is NOT wired (wireArtifactsDistribution not
    // called) to avoid the circular dep — it's tested in isolation.
    const cert = 'arn:aws:acm:us-east-1:123456789012:certificate/test';
    const config = createMockConfig({
      domainName: 'example.com',
      infrastructureHostedZoneDomain: 'example.com',
      certificateArn: cert,
      frontend: { cloudFrontPriceClass: 'PriceClass_100', certificateArn: cert },
      artifacts: { retentionDays: 90, extraFrameAncestors: [], certificateArn: cert },
      mcpSandbox: { extraFrameAncestors: [], certificateArn: cert },
      fineTuning: {},
    });
    const app = new cdk.App();
    mockSsmContext(app, config);

    const platform = new PlatformStack(app, 'Platform', {
      config,
      env: { account: MOCK_ACCOUNT, region: MOCK_REGION },
    });
    platform.wireSpaDistribution();
    // NOTE: wireArtifactsDistribution() NOT called — avoids circular dep

    const backend = new BackendStack(app, 'Backend', {
      config,
      platform,
      env: { account: MOCK_ACCOUNT, region: MOCK_REGION },
    });
    template = Template.fromStack(backend);
  });

  describe('App API Fargate service', () => {
    it('creates an ECS task definition', () => {
      template.resourceCountIs('AWS::ECS::TaskDefinition', 1);
    });

    it('creates an ECS Fargate service', () => {
      template.resourceCountIs('AWS::ECS::Service', 1);
    });

    it('creates a target group', () => {
      template.resourceCountIs('AWS::ElasticLoadBalancingV2::TargetGroup', 1);
    });

    it('creates a listener rule', () => {
      template.resourceCountIs('AWS::ElasticLoadBalancingV2::ListenerRule', 1);
    });

    it('creates an ECS security group', () => {
      // App API ECS SG + SageMaker SG
      template.resourceCountIs('AWS::EC2::SecurityGroup', 2);
    });

    it('creates auto-scaling targets', () => {
      template.resourceCountIs('AWS::ApplicationAutoScaling::ScalableTarget', 1);
    });

    it('creates auto-scaling policies', () => {
      template.resourceCountIs('AWS::ApplicationAutoScaling::ScalingPolicy', 2);
    });

    it('creates an auto-named log group for the task', () => {
      // Asserting `LogGroupName` is intentionally omitted — we want
      // CDK to auto-generate the name so a failed-deploy orphan
      // can't collide with a redeploy. Also can't `resourceCountIs`
      // because BackendStack contains multiple log groups
      // (artifact-render, rag-ingestion, AgentCore Runtime, AgentCore
      // Memory, app-api). Just verify at least one exists by
      // matching the retention.
      template.hasResourceProperties('AWS::Logs::LogGroup', {
        RetentionInDays: 7,
      });
    });
  });

  describe('AgentCore resources', () => {
    it('creates AgentCore Runtime', () => {
      template.resourceCountIs('AWS::BedrockAgentCore::Runtime', 1);
    });

    it('does NOT create AgentCore Memory (hoisted to PlatformStack)', () => {
      // Memory was hoisted to PlatformStack in Phase 1 of the
      // platform-as-bootstrap refactor. BackendStack consumes it
      // via typed cross-stack ref now.
      template.resourceCountIs('AWS::BedrockAgentCore::Memory', 0);
    });

    it('does NOT create Code Interpreter Custom (hoisted to PlatformStack)', () => {
      template.resourceCountIs('AWS::BedrockAgentCore::CodeInterpreterCustom', 0);
    });

    it('does NOT create Browser Custom (hoisted to PlatformStack)', () => {
      template.resourceCountIs('AWS::BedrockAgentCore::BrowserCustom', 0);
    });

    it('does NOT create AgentCore Gateway (hoisted to PlatformStack)', () => {
      // Gateway hoist landed in Phase 2 of the platform-as-bootstrap
      // refactor. Backend no longer touches the Gateway.
      template.resourceCountIs('AWS::BedrockAgentCore::Gateway', 0);
    });
  });

  describe('RAG Ingestion Lambda', () => {
    it('creates the ingestion Lambda function', () => {
      // FunctionName is auto-generated by CDK to avoid collisions
      // with orphans from failed deploys; verify the function exists
      // by counting Lambda resources rather than asserting a name.
      // Two Lambda functions in BackendStack after Phase 3:
      //   1. RAG ingestion (DockerImageFunction)
      //   2. CFN custom-resource handler (S3 bucket notification
      //      configurator, auto-injected by CDK when
      //      addEventNotification is wired from an imported bucket)
      // (artifact-render moved to PlatformStack in Phase 3.)
      template.resourceCountIs('AWS::Lambda::Function', 2);
    });

    it('creates S3 bucket notification for the Lambda', () => {
      template.resourceCountIs('Custom::S3BucketNotifications', 1);
    });

    it('publishes the auto-generated ingestion function name to SSM', () => {
      template.hasResourceProperties('AWS::SSM::Parameter', {
        Name: '/test-project/rag/ingestion-function-name',
      });
    });
  });

  describe('Artifact Render Lambda', () => {
    it('does NOT live in BackendStack (hoisted to PlatformStack in Phase 3)', () => {
      const params = template.findResources('AWS::SSM::Parameter', {
        Properties: { Name: '/test-project/artifacts/render-function-name' },
      });
      expect(Object.keys(params).length).toBe(0);
    });
  });

  describe('SageMaker Fine-Tuning', () => {
    it('creates the SageMaker execution role', () => {
      template.hasResourceProperties('AWS::IAM::Role', {
        RoleName: 'test-project-sagemaker-exec-role',
      });
    });

    it('creates the SageMaker security group', () => {
      template.hasResourceProperties('AWS::EC2::SecurityGroup', {
        GroupDescription: 'Security group for SageMaker training jobs - outbound HTTPS only',
      });
    });
  });

  describe('IAM roles', () => {
    it('creates the AgentCore runtime execution role', () => {
      template.hasResourceProperties('AWS::IAM::Role', {
        RoleName: 'test-project-agentcore-runtime-role',
      });
    });

    it('does NOT create the AgentCore memory execution role (hoisted to PlatformStack)', () => {
      // Memory role moved with the Memory resource in Phase 1.
      const roles = template.findResources('AWS::IAM::Role', {
        Properties: { RoleName: 'test-project-agentcore-memory-role' },
      });
      expect(Object.keys(roles).length).toBe(0);
    });

    it('does NOT create the gateway execution role (hoisted to PlatformStack)', () => {
      const roles = template.findResources('AWS::IAM::Role', {
        Properties: { RoleName: 'test-project-gateway-role' },
      });
      expect(Object.keys(roles).length).toBe(0);
    });
  });

  describe('No data resources in Backend', () => {
    it('creates zero DynamoDB tables', () => {
      // PlatformStack owns 100% of the data layer. BackendStack is
      // pure compute — Fargate, Lambdas, CloudFront. The previous
      // "assistants table is local" carve-out has been removed; the
      // construct is decommissioned.
      template.resourceCountIs('AWS::DynamoDB::Table', 0);
    });

    it('creates zero S3 buckets', () => {
      template.resourceCountIs('AWS::S3::Bucket', 0);
    });

    it('does NOT create the artifacts CloudFront distribution (hoisted to PlatformStack in Phase 3)', () => {
      template.resourceCountIs('AWS::CloudFront::Distribution', 0);
    });
  });

  describe('SSM parameters', () => {
    it('does NOT publish gateway SSM parameters (hoisted to PlatformStack)', () => {
      const gatewayParams = template.findResources('AWS::SSM::Parameter', {
        Properties: { Name: '/test-project/gateway/url' },
      });
      expect(Object.keys(gatewayParams).length).toBe(0);
    });

    it('publishes RAG ingestion Lambda ARN', () => {
      template.hasResourceProperties('AWS::SSM::Parameter', {
        Name: '/test-project/rag/ingestion-lambda-arn',
      });
    });
  });
});
