// Generated by scripts/gen-version.js. Do not edit by hand.
// Production builds overwrite this with the value from the root VERSION file
// via the npm `prebuild` hook.
export const VERSION: string = 'dev';
