#!/usr/bin/env node
// Reads the monorepo's root VERSION file and writes src/version.ts.
// Wired into npm `prebuild` so production bundles ship with the real
// version baked in. The committed src/version.ts placeholder ('dev')
// keeps `ng test` and IDE imports working on a fresh clone.

const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '..', '..', '..');
const versionFile = path.join(repoRoot, 'VERSION');
const outFile = path.join(__dirname, '..', 'src', 'version.ts');

const version = fs.readFileSync(versionFile, 'utf8').trim() || 'unknown';

// Annotated as `string` (not the literal) so consumers can compare against
// other strings (e.g. 'dev') without TS narrowing the comparison to never.
const contents = `// Generated by scripts/gen-version.js. Do not edit by hand.
// Production builds overwrite this with the value from the root VERSION file
// via the npm \`prebuild\` hook.
export const VERSION: string = '${version}';
`;

fs.writeFileSync(outFile, contents);
console.log(`✏️  src/version.ts ← ${version}`);
